before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y nasm gcc-7-base grub2
language: c
script: make all
include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - nasm
            - grub2
      env:
            - MATRIX_EVAL="CC=gcc"
